name: Deploy ke cPanel (FTP)

on:
  push:
    branches:
      - main   # ganti kalau pakai branch lain

jobs:
  ftp-deploy:
    name: Upload via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy ke server via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          server-dir: ${{ secrets.FTP_DIR_NAME }}
          dangerous-clean-slate: false
